### ISSUE TITLE
The use Coindesk; namespace

### ISSUE THREAD

**Issue by cletuskingdom** [AndikanGabriel/coindesk#2]
I followed your description yesterday and everything worked fine, but reopening the project this morning, i get this error: 

![image](https://user-images.githubusercontent.com/38631504/103455131-886f8400-4cea-11eb-9e0c-85c379e024ca.png)
Here is my web.php file:

![image](https://user-images.githubusercontent.com/38631504/103455150-b6ed5f00-4cea-11eb-8b27-9c1e5a775cf6.png)

but on commenting the namespace 

![image](https://user-images.githubusercontent.com/38631504/103455159-d3899700-4cea-11eb-91a5-eadc3402809e.png)

I was now able to serve the project, please is that an issue, or we could just continue by commenting it?

**Comment by cletuskingdom** [comment]
I just used it in a controller and noticed that i have to provide the namespace, and it did serve without issue.
![image](https://user-images.githubusercontent.com/38631504/103457285-2caef600-4cfe-11eb-9b02-83beda7845bb.png)

**Comment by AndikanGabriel** [comment]
@cletuskingdom I'm glad that you were able to resolve it. You can find a detailed explanation of the error you experienced on StackOverflow [here](https://stackoverflow.com/a/23747053) and [here](https://stackoverflow.com/a/41441526).

**Comment by cletuskingdom** [comment]
Okay, Thanks.

While I check it out, please how do I get the price of ethereum?

**Comment by AndikanGabriel** [comment]
Do you mean converting from BTC to ETH?

```php
```

**Comment by AndikanGabriel** [comment]
It is not possible in this version due to Coindesk's API limitation. An update will be made, for such actions to take place.

**Comment by cletuskingdom** [comment]
Okay, Thank you very much.
